/* automatically generated by rust-bindgen 0.63.0 */

pub const OwnershipPolicy_NonOwning: OwnershipPolicy = 0;
pub const OwnershipPolicy_Copy: OwnershipPolicy = 1;
pub const OwnershipPolicy_Owning: OwnershipPolicy = 2;
pub type OwnershipPolicy = ::std::os::raw::c_uint;
extern "C" {
    #[link_name = "\u{1}__Z10return_intv"]
    pub fn return_int() -> ::std::os::raw::c_int;
}
